# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2IxMTZjNDRjMzU4ZjI3YTM1MmU1ZTczOGQ4ZGE2MjE2YjkyZWM5Zjc2NDY4MjIyNzNhYTEyZTdjZTI1NmQxMjgxYTFkMjI4NzE2MDlhMTJhZGVmZGYwNzQ5MTM3NmEwY2JlNTM3MTJkMTdlNmUwOTk4MGM3MTM1YjhjYzlhZTA=
